In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

import tensorflow as tf
from tensorflow import keras
import pandas as pd
import seaborn as sns; sns.set()
import numpy as np

train = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Dataset/house-prices-advanced-regression-techniques/train_preprocessed.csv")
test = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Dataset/house-prices-advanced-regression-techniques/test_preprocessed.csv")

train_original = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Dataset/house-prices-advanced-regression-techniques/train.csv")
y = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Dataset/house-prices-advanced-regression-techniques/y_train.csv")
y = y['0']

Mounted at /content/gdrive/


In [ ]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)

In [ ]:
d = tf.multiply(a, b)
e = tf.add(c, d)

In [ ]:
#  연산그래프 실행
@tf.function
def forward() :
    a = tf.constant(5)
    b = tf.constant(2)
    c = tf.constant(3)

    d = tf.multiply(a, b)  # a * b
    e = tf.add(c, b)  # c + b
    f = tf.subtract(d, e)  # d - e
    
    return f

outs = forward()
print("outs = {}".format(outs))

outs = 5


In [ ]:
g = tf.Graph()
h = tf.Graph()
with g.as_default():
  a = tf.constant(5)
  print('a 노드가 g 그래프와 연결 되어 있나? :', a.graph is g)
  print('a 노드가 h 그래프와 연결 되어 있나? :', a.graph is h)

a 노드가 g 그래프와 연결 되어 있나? : True
a 노드가 h 그래프와 연결 되어 있나? : False


In [ ]:
g = tf.Graph()
with g.as_default():
  # Define operations and tensors in `g`.
  c = tf.constant(30.0)
  assert c.graph is g

In [ ]:
a = tf.constant(5)
b = tf.constant(2)
d = tf.multiply(a, b)

@tf.function
def sess() :
  return d

outs = sess()
print("outs = {}".format(outs))

outs = 10


# Tesnorflow: User Defined Model

In [ ]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

print(t,'\n')
print(t.shape)
print(t.dtype, '\n')
print(t+10, '\n')
print(tf.square(t), '\n')
print(t@tf.transpose(t))

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32) 

(2, 3)
<dtype: 'float32'> 

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32) 

tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32) 

tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [ ]:
a = np.array([2., 4., 5.])
tf.constant(a)
t.numpy()
print(tf.square(a))
print(np.square(t))

tf.Tensor([ 4. 16. 25.], shape=(3,), dtype=float64)
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [ ]:
try: tf.constant(3) + tf.constant(3.)
except: print("type 변환은 사용자가 직접\n")

t2 = tf.constant(40., dtype = tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

type 변환은 사용자가 직접



<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [ ]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
print(v, '\n')

v.assign(2*v); print(v, '\n')
v[0, 1].assign(42); print(v, '\n')
v[:, 2].assign([0., 1.]); print(v, '\n')
v.scatter_nd_update(indices = [[0, 0], [1, 2]], updates = [100., 200.]) # 개별 수정

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)> 

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)> 

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)> 

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  0.],
       [ 8., 10.,  1.]], dtype=float32)> 



<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10., 200.]], dtype=float32)>

In [ ]:
# Huber loss 구현 -> 공식 keras에는 없으나 keras.loss.Huber에 존재하기는 함
def huber_fn(y_true, y_pred):
  error = y_true - y_pred
  is_small_error = tf.abs(error)<1
  squared_loss = tf.square(error)/2
  linear_loss = tf.abs(error)-0.5
  return tf.where(is_small_error, squared_loss, linear_loss)

In [ ]:
from tensorflow import keras
drop_rate = 0.5

model = keras.models.Sequential()
model.add(keras.layers.Dense(32, activation = 'relu', input_dim= train.shape[1]))
model.add(tf.keras.layers.Dropout(drop_rate))
model.add(keras.layers.Dense(64, activation = 'relu'))
model.add(tf.keras.layers.Dropout(drop_rate))
model.add(keras.layers.Dense(32, activation = 'relu'))
model.add(tf.keras.layers.Dropout(drop_rate))
model.add(keras.layers.Dense(1)) # to classify
model.compile(loss = huber_fn, optimizer = keras.optimizers.Adam(learning_rate=0.0001))
model.fit(train, y, validation_split=0.1, batch_size=32,epochs=100)

In [ ]:
(X_train, y_train), (X_test, y_test) = keras.datasets.imdb.load_data()
print(X_train[0][:10])

17473536/17464789 [==============================] - 0s 0us/step


[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65]

In [ ]:
word_index = keras.datasets.imdb.get_word_index()
id_to_word = {id_ + 3: word for word, id_ in word_index.items()}
for id_, token in enumerate(("<pad>", "<sos>", "<unk>")):
  id_to_word[id_] = token

" ".join([id_to_word[id_] for id_ in X_train[0][:10]])

1654784/1641221 [==============================] - 0s 0us/step


'<sos> this film was just brilliant casting location scenery story'

In [ ]:
import tensorflow_datasets as tfds

datasets, info = tfds.load("imdb_reviews", as_supervised = True, with_info = True)
train_size = info.splits["train"].num_examples

def preprocess(X_batch, y_batch):
  X_batch = tf.strings.substr(X_batch, 0, 300) # 처음 300 글자만 남긴다
  X_batch = tf.strings.regex_replace(X_batch, b"<br\\s*/?>", b" ") # 
  X_batch = tf.strings.regex_replace(X_batch, b"[^a-zA-Z']", b" ")
  X_batch = tf.strings.split(X_batch) # review를 공백으로 나눈다

  return X_batch.to_tensor(default_value = b"<pad>"), y_batch

from collections import Counter
vocabulary = Counter()

for X_batch, y_batch in datasets["train"].batch(32).map(preprocess):
  for review in X_batch:
    vocabulary.update(list(review.numpy()))
  
print(vocabulary.most_common()[:3])

vocab_size = 10000
truncated_vocabulary = [word for word, count in vocabulary.most_common()[:vocab_size]] # 어휘는 10000개로 제한하자

words = tf.constant(truncated_vocabulary) # 어휘 사전 정의 
word_ids = tf.range(len(truncated_vocabulary), dtype = tf.int64) # id 0번 부터 생성
vocab_init = tf.lookup.KeyValueTensorInitializer(words, word_ids) # 룩업테이블을 위한 초기화 객체 생성 words를 id에 대응
num_oov_buckets = 1000 
table = tf.lookup.StaticVocabularyTable(vocab_init, num_oov_buckets) # 1000개의 bucket table을 사용하는 lookup table 생성 -> 룩업 테이블은 해시값을 계산하여 bucket에 할당

table.lookup(tf.constant([b"This movie was faaaaaantastic".split()])) # faaaaaantastic라는 단어는 없으므로 10000보다 큰 id를 가진 oov 버킷 중 하나에 매핑

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteLZB1ND/imdb_reviews-train.tfrecord


  0%|          | 0/25000 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteLZB1ND/imdb_reviews-test.tfrecord


  0%|          | 0/25000 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteLZB1ND/imdb_reviews-unsupervised.tfrecord


  0%|          | 0/50000 [00:00<?, ? examples/s]

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.
[(b'<pad>', 214309), (b'the', 61137), (b'a', 38564)]


<tf.Tensor: shape=(1, 4), dtype=int64, numpy=array([[   22,    12,    11, 10053]])>

In [ ]:
def encode_words(X_batch, y_batch):
  return table.lookup(X_batch), y_batch

train_set = datasets["train"].batch(32).map(preprocess)
train_set = train_set.map(encode_words).prefetch(1)

embed_size = 128
model = keras.models.Sequential([
                                 keras.layers.Embedding(vocab_size + num_oov_buckets, embed_size,
                                                        input_shape = [None]), # 단어 ID를 embedding으로 변환하는 Embedding 층
                                 keras.layers.GRU(128, return_sequences = True),
                                 keras.layers.GRU(128),
                                 keras.layers.Dense(1, activation = "sigmoid")
])
model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])
history = model.fit(train_set, epochs = 5)

In [ ]:
K = keras.backend
inputs = keras.layers.Input(shape = [None])
mask = keras.layers.Lambda(lambda inputs: K.not_equal(inputs, 0))(inputs) # Mask Tensor로 ID가 0인 위치는 False, other wise True -> padding token 등을 무시할 수 있도록 하는 것이 masking
z = keras.layers.Embedding(vocab_size + num_oov_buckets, embed_size)(inputs) # sequence 출력
z = keras.layers.GRU(128, return_sequences = True)(z, mask = mask) # 마지막 time step의 output return
z = keras.layers.GRU(128)(z, mask = mask)
outputs = keras.layers.Dense(1, activation = "sigmoid")(z)
model = keras.Model(inputs = [inputs], outputs = [outputs])

## Encoder-Decoder Network

In [ ]:
import tensorflow_addons as tfa

encoder_inputs = keras.layers.Input(shape = [None], dtype = np.int32)
decoder_inputs = keras.layers.Input(shape = [None], dtype = np.int32)
sequence_lengths = keras.layers.Input(shape = [], dtype= np.int32)

embeddings = keras.layers.Embedding(vocab_size, embed_size)
encoder_embeddings = embeddings(encoder_inputs)
decoder_embeddings = embeddings(decoder_inputs)

encoder = keras.layers.LSTM(512, return_sate = True)
encoder_outputs, state_h, state_c = encoder(encode_embeddings)
encoder_state = [state_h, state_c]

sampler = tfa.seq2seq.sampler.TrainingSampler()

decoder_cell = keras.layers.LSTMCell(512)
output_layer = keras.layers.Dense(vocab_size)
decoder = tfa.seq2seq.basic_decoder.basicDecoder(decoder_cell, sampler, output_layer = output_layer)

final_outputs, final_state, final_sequence_lengths = decoder(
    decoder_embeddings, initial_state = encoder_state,
    sequence_length = sequence_lengths)
Y_proba = tf.nn.softmax(final_outputs.rnn_output)

model = keras.Model(inputs = [encoder_inputs, decoder_inputs, sequence_lengths], outputs = [Y_proba])